approvals:
  # PR needs at least 1 approval
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^:\\+1:$"
  from:
    # commenter must be either one of:
    # a public zalando org member
    orgs:
      - zalando
    # a collaborator of the repo
    #collaborators: true
    # this guy
    #users:
    #  - mfellner
    #  - prayerslayer
commit:
  message:
    patterns:
      - "^(?:(?:[a-zA-Z0-9_\\-]*|[a-zA-Z0-9_\\-]+\\/[a-zA-Z0-9_\\-]+)#|GH-)\\d+$"
      - "^#?[A-Z]+-[0-9]+"
